// src/lib/rewards-engine.ts
//
// Server-side reward issuance + redemption logic — TRANSACTIONAL + IDEMPOTENT.
//
// CRITICAL INVARIANT:
//   This module does NOT open its own Prisma transaction. The caller wraps
//   every call in `withTransaction(async (tx) => { ... })` (from src/lib/db.ts)
//   and passes the `tx` (Prisma.TransactionClient) into these functions. This
//   keeps all reads/writes inside the same snapshot + lock window so:
//     - Balance checks can't race with concurrent redemptions
//     - Ledger entries are committed atomically with the triggering mutation
//       (e.g., the order PICKED_UP transition or the gift PAID transition)
//     - Reward issuance is idempotent — a duplicate key just returns the
//       existing ledger entry rather than issuing duplicate points
//
// Governance (blueprint §17 REWARDS ENGINE + plan §1.D):
//   - Earn fires on PICKED_UP only (prevents cancellation farming)
//   - Ledger-based balance (immutable RewardLedgerEntry rows)
//   - Idempotency via RewardLedgerEntry.idempotencyKey @@unique constraint (Task 1A schema)
//   - One entry per (userId, idempotencyKey)
//   - 365-day expiry via cron (deferred — lazy expiry in MVP)

import { Prisma } from '@prisma/client'
import { buildIdempotencyKey } from './reward-rules'

// ---------------------------------------------------------------------------
// Product-foundation Prisma model delegates
// ---------------------------------------------------------------------------
// Task 1A will add the RewardAccount / RewardLedgerEntry / RewardRedemption
// models to prisma/schema.prisma. Until that schema migration lands, these
// properties don't exist on Prisma.TransactionClient (they're generated by
// `prisma generate` from the schema).
//
// We declare a permissive extension type so rewards-engine compiles against
// the pre-migration client. Once Task 1A applies the schema + runs
// `bun run db:generate`, the real typed delegates replace these `any` stubs
// (the assignment is structurally compatible — `any` is assignable to/from
// any strongly-typed Prisma delegate).
//
// Route handlers (Task 5A) cast their `tx` to `RewardTx` when calling these
// helpers; the cast becomes a no-op once Prisma generates the real types.
export interface RewardPrismaModels {
  rewardAccount: {
    upsert(args: any): Promise<any>
    findUnique(args: any): Promise<any>
    update(args: any): Promise<any>
    create(args: any): Promise<any>
  }
  rewardLedgerEntry: {
    create(args: any): Promise<any>
    findFirst(args: any): Promise<any>
    findMany(args: any): Promise<any>
    aggregate(args: any): Promise<{ _sum: { points: number | null } }>
  }
  rewardRedemption: {
    create(args: any): Promise<any>
    findUnique(args: any): Promise<any>
  }
}

/**
 * Transaction client extended with the product-foundation reward models.
 *
 * Callers wrap their `withTransaction` body in a cast to this type:
 *
 *   await withTransaction(async (tx) => {
 *     await issueReward(tx as unknown as RewardTx, { ... })
 *   })
 *
 * Once Task 1A's schema migration lands + `bun run db:generate` runs,
 * Prisma generates the real typed delegates on Prisma.TransactionClient
 * and the cast becomes a strict no-op.
 */
export type RewardTx = Prisma.TransactionClient & RewardPrismaModels

// ---------------------------------------------------------------------------
// Public row types — mirror the Prisma models (Task 1A schema).
// Defined here so callers don't need to import Prisma types (which don't
// exist until Task 1A lands). When Task 1A generates the Prisma client,
// these interfaces remain structurally compatible.
// ---------------------------------------------------------------------------

export interface RewardAccountRow {
  id: string
  userId: string
  balance: number // points (positive integer)
  lifetimeEarned: number
  lifetimeRedeemed: number
  updatedAt: Date
}

export interface RewardLedgerEntryRow {
  id: string
  userId: string
  type: string // 'EARN' | 'REDEEM' | 'EXPIRE' | 'ADJUST'
  points: number // signed: + for EARN, - for REDEEM/EXPIRE
  orderId: string | null
  ruleId: string | null
  giftId: string | null
  groupOrderId: string | null
  referralUserId: string | null
  idempotencyKey: string
  expiresAt: Date | null
  createdAt: Date
}

export interface RewardRedemptionRow {
  id: string
  userId: string
  ledgerEntryId: string
  rewardType: string // 'PERCENT_DISCOUNT' | 'FIXED_DISCOUNT' | 'FREE_ITEM' | 'VENDOR_SPECIFIC'
  discountValue: string
  orderId: string | null
  redemptionCode: string
  redeemedAt: Date
}

// ---------------------------------------------------------------------------
// Public function param/result types
// ---------------------------------------------------------------------------

export interface IssueRewardParams {
  userId: string
  ruleKey: string
  points: number
  orderId?: string
  giftId?: string
  groupOrderId?: string
  referralUserId?: string
  /** Optional explicit idempotency key (defaults to buildIdempotencyKey(userId, ruleKey, orderId)). */
  idempotencyKey?: string
  /** Optional ISO timestamp for when the earned points expire (EARN entries only). */
  expiresAt?: Date
  /**
   * Optional FK to RewardRule.id (Task 5A additive). When the caller has
   * already resolved the RewardRule row by key, populate this so the ledger
   * entry joins to its rule. Left null when the rule isn't in the DB (the
   * RewardLedgerEntry.ruleId column is nullable per Task 1A schema).
   */
  ruleId?: string
}

export interface IssueRewardResult {
  ledgerEntry: RewardLedgerEntryRow
  newBalance: number
  /** True if this call found an existing entry (no-op). False if a new entry was created. */
  deduplicated: boolean
}

export interface RedeemRewardParams {
  userId: string
  points: number
  orderId?: string
  /** Optional redemption code override; auto-generated if omitted. */
  redemptionCode?: string
  rewardType?: 'PERCENT_DISCOUNT' | 'FIXED_DISCOUNT' | 'FREE_ITEM' | 'VENDOR_SPECIFIC'
  discountValue?: string
}

export interface RedeemRewardResult {
  redemption: RewardRedemptionRow
  newBalance: number
}

// ---------------------------------------------------------------------------
// Internal helpers (NOT exported — pure helpers local to this module)
// ---------------------------------------------------------------------------

/**
 * Generate a single-use redemption code: `SNZ-RWD-XXXXXX` (6 chars from a
 * legibility-friendly alphabet — no I/O/0/1 to avoid readback confusion).
 *
 * Random, not cryptographically secure — the uniqueness guarantee comes from
 * the RewardRedemption.redemptionCode @@unique constraint (Task 1A schema),
 * so a collision will surface as a P2002 error from Prisma and the caller
 * can retry with a fresh code.
 */
function genRedemptionCode(): string {
  const alphabet = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789'
  let code = ''
  for (let i = 0; i < 6; i++) {
    code += alphabet[Math.floor(Math.random() * alphabet.length)]
  }
  return `SNZ-RWD-${code}`
}

/**
 * Lazy-create the reward account row if it doesn't exist (idempotent upsert).
 * Used as a precondition by both issue + redeem flows.
 *
 * MUST be called inside the caller's transaction (uses `tx`).
 */
async function getOrCreateAccount(tx: RewardTx, userId: string): Promise<RewardAccountRow> {
  const account = (await tx.rewardAccount.upsert({
    where: { userId },
    create: {
      userId,
      balance: 0,
      lifetimeEarned: 0,
      lifetimeRedeemed: 0,
    },
    update: {},
  })) as RewardAccountRow
  return account
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Issue reward points IDEMPOTENTLY.
 *
 * - If a RewardLedgerEntry with the same idempotencyKey already exists for
 *   this user, returns it WITHOUT creating a new entry or modifying the
 *   balance. (This is the "no duplicate reward on retry" guarantee —
 *   blueprint §17.)
 * - Otherwise, creates a new EARN ledger entry and atomically increments the
 *   account balance (within the caller's transaction).
 *
 * MUST be called inside `withTransaction(async (tx) => { ... })` — the caller
 * passes the transaction client as the first argument. This module does NOT
 * open its own transaction (governance: financial mutations must share the
 * caller's snapshot + lock window so balance checks can't race).
 *
 * @param tx      Caller's Prisma.TransactionClient (cast to RewardTx)
 * @param params  Issuance details (userId, ruleKey, points, idempotencyKey, etc.)
 * @returns       The ledger entry + new balance + deduplicated flag
 */
export async function issueReward(
  tx: RewardTx,
  params: IssueRewardParams,
): Promise<IssueRewardResult> {
  const {
    userId,
    ruleKey,
    points,
    orderId,
    giftId,
    groupOrderId,
    referralUserId,
    idempotencyKey,
    expiresAt,
    ruleId,
  } = params

  if (!userId) throw new Error('issueReward: userId required')
  if (!ruleKey) throw new Error('issueReward: ruleKey required')
  if (!Number.isInteger(points) || points <= 0) {
    throw new Error(`issueReward: points must be a positive integer (got ${points})`)
  }

  const key = idempotencyKey ?? buildIdempotencyKey(userId, ruleKey, orderId)

  // 1. Idempotency check — if a ledger entry already exists for this key,
  //    return it WITHOUT issuing duplicate points.
  const existing = (await tx.rewardLedgerEntry.findFirst({
    where: { userId, idempotencyKey: key },
  })) as RewardLedgerEntryRow | null

  if (existing) {
    const account = await getOrCreateAccount(tx, userId)
    return {
      ledgerEntry: existing,
      newBalance: account.balance,
      deduplicated: true,
    }
  }

  // 2. Ensure account exists.
  const account = await getOrCreateAccount(tx, userId)

  // 3. Create the EARN ledger entry (signed +points).
  const ledgerEntry = (await tx.rewardLedgerEntry.create({
    data: {
      userId,
      type: 'EARN',
      points,
      orderId: orderId ?? null,
      ruleId: ruleId ?? null, // optional FK to RewardRule.id (caller-resolved)
      giftId: giftId ?? null,
      groupOrderId: groupOrderId ?? null,
      referralUserId: referralUserId ?? null,
      idempotencyKey: key,
      expiresAt: expiresAt ?? null,
    },
  })) as RewardLedgerEntryRow

  // 4. Atomically increment the cached balance + lifetimeEarned.
  const updated = (await tx.rewardAccount.update({
    where: { userId },
    data: {
      balance: { increment: points },
      lifetimeEarned: { increment: points },
    },
  })) as RewardAccountRow

  return {
    ledgerEntry,
    newBalance: updated.balance,
    deduplicated: false,
  }
}

/**
 * Redeem reward points for a discount code. Validates balance inside the
 * caller's transaction, then atomically:
 *   - Creates a REDEEM ledger entry (signed -points)
 *   - Creates a RewardRedemption row (1:1 with the ledger entry, single-use code)
 *   - Decrements the account balance + increments lifetimeRedeemed
 *
 * MUST be called inside `withTransaction(async (tx) => { ... })`.
 *
 * Throws if the user has insufficient balance. The throw propagates to the
 * caller's transaction, which Prisma rolls back automatically (so no partial
 * state is committed).
 *
 * @param tx      Caller's Prisma.TransactionClient (cast to RewardTx)
 * @param params  Redemption details (userId, points, optional orderId + code override)
 * @returns       The redemption row + new balance
 */
export async function redeemReward(
  tx: RewardTx,
  params: RedeemRewardParams,
): Promise<RedeemRewardResult> {
  const {
    userId,
    points,
    orderId,
    redemptionCode,
    rewardType = 'FIXED_DISCOUNT',
    discountValue = '0',
  } = params

  if (!userId) throw new Error('redeemReward: userId required')
  if (!Number.isInteger(points) || points <= 0) {
    throw new Error(`redeemReward: points must be a positive integer (got ${points})`)
  }

  const account = await getOrCreateAccount(tx, userId)
  if (account.balance < points) {
    throw new Error(
      `redeemReward: insufficient balance (have ${account.balance}, need ${points})`,
    )
  }

  // 1. Create the REDEEM ledger entry (signed -points).
  //    Idempotency key includes a timestamp + random suffix because redemptions
  //    are NOT one-per-order (a user can redeem multiple times against the same
  //    order — e.g., partial redemptions). The idempotency boundary is the
  //    unique ledger entry ID itself.
  const redeemKey =
    buildIdempotencyKey(userId, 'REDEEM', orderId) +
    `:${Date.now()}:${Math.random().toString(36).slice(2, 8)}`

  const ledgerEntry = (await tx.rewardLedgerEntry.create({
    data: {
      userId,
      type: 'REDEEM',
      points: -points,
      orderId: orderId ?? null,
      ruleId: null,
      giftId: null,
      groupOrderId: null,
      referralUserId: null,
      idempotencyKey: redeemKey,
      expiresAt: null,
    },
  })) as RewardLedgerEntryRow

  // 2. Create the single-use redemption code (1:1 with the ledger entry).
  const code = redemptionCode || genRedemptionCode()
  const redemption = (await tx.rewardRedemption.create({
    data: {
      userId,
      ledgerEntryId: ledgerEntry.id,
      rewardType,
      discountValue,
      orderId: orderId ?? null,
      redemptionCode: code,
    },
  })) as RewardRedemptionRow

  // 3. Atomically decrement balance + bump lifetimeRedeemed.
  const updated = (await tx.rewardAccount.update({
    where: { userId },
    data: {
      balance: { decrement: points },
      lifetimeRedeemed: { increment: points },
    },
  })) as RewardAccountRow

  return {
    redemption,
    newBalance: updated.balance,
  }
}

/**
 * Background job: expire stale EARN entries whose `expiresAt` has passed.
 *
 * PLACEHOLDER — full implementation deferred (plan §1.D: "365-day expiry via
 * cron (deferred — lazy expiry in MVP)"). When implemented:
 *   - Find RewardLedgerEntry rows where type='EARN' AND expiresAt < now() AND
 *     no matching EXPIRE entry exists (join via idempotencyKey prefix).
 *   - For each, create a matching EXPIRE entry (signed -points) with a
 *     derived idempotencyKey `${EARN_KEY}:expire`.
 *   - Decrement the account balance + bump a lifetimeExpired counter (TBD).
 *
 * MUST be called from a cron / scheduled job — NOT from a request handler
 * (long-running batches don't belong in the request path).
 *
 * @returns  Counts of expired entries + total points expired. Always {0,0} until implemented.
 */
export async function expireStaleRewards(): Promise<{
  expiredCount: number
  expiredPoints: number
}> {
  // TODO: implement once Task 1A schema lands + cron scheduler is wired.
  // For now, return zero — no-op placeholder so callers can invoke safely.
  return { expiredCount: 0, expiredPoints: 0 }
}
